import type {
  BaseEntity,
  EntityId,
  ISODateString,
  ISODateTimeString,
} from './common'

export type DailyReportStatus =
  | 'Draft'
  | 'Submitted'
  | 'InReview'
  | 'Approved'
  | 'Returned'
  | 'Rejected'
  | 'Archived'

export type ShiftType = 'day' | 'night' | 'other'

export type WeatherCondition =
  | 'clear'
  | 'cloudy'
  | 'rain'
  | 'snow'
  | 'windy'
  | 'storm'
  | 'other'

export type WorkCategory =
  | 'earthworks'
  | 'concrete'
  | 'steel_structure'
  | 'mechanical'
  | 'electrical'
  | 'piping'
  | 'roadworks'
  | 'civil'
  | 'demolition'
  | 'inspection'
  | 'other'

export type QuantityUnit =
  | 'm3'
  | 'm2'
  | 'm'
  | 'ton'
  | 'kg'
  | 'pcs'
  | 'hr'
  | 'day'
  | 'percent'
  | 'other'

export type YesNo = 'yes' | 'no'

export type EquipmentStatus =
  | 'working'
  | 'idle'
  | 'breakdown'
  | 'maintenance'

export type QualityResult =
  | 'passed'
  | 'failed'
  | 'hold'
  | 'not_applicable'

export type CorrectiveActionStatus =
  | 'open'
  | 'in_progress'
  | 'closed'
  | 'not_required'

export interface WorkActivitySummary {
  workAreaId?: EntityId
  locationId?: EntityId
  disciplineId?: EntityId
  tradeId?: EntityId
  activityId?: EntityId
  costCode?: string
  wbsCode?: string
  description: string
  plannedQuantity?: number
  actualQuantity?: number
  unitOfMeasure?: string
  percentComplete?: number
}

export interface ManpowerSummaryEntry {
  contractorId?: EntityId
  tradeId?: EntityId
  roleName?: string
  workerCount: number
  regularHours?: number
  overtimeHours?: number
  notes?: string
}

export interface ManpowerSummary {
  totalWorkers: number
  notes?: string
  entries?: ManpowerSummaryEntry[]
}

export interface EquipmentSummaryEntry {
  equipmentId?: EntityId
  equipmentType?: string
  equipmentName: string
  quantity?: number
  workingHours?: number
  idleHours?: number
  breakdownHours?: number
  notes?: string
}

export interface EquipmentSummary {
  totalEquipment: number
  notes?: string
  entries?: EquipmentSummaryEntry[]
}

export interface MaterialSummaryEntry {
  materialId?: EntityId
  materialName: string
  quantity?: number
  unitOfMeasure?: string
  notes?: string
}

export interface MaterialSummary {
  notes?: string
  entries?: MaterialSummaryEntry[]
}

export interface DelaySummary {
  hasDelay: boolean
  delayHours?: number
  reason?: string
  responsibleParty?: string
  impact?: string
  mitigation?: string
}

export interface SafetySummary {
  incidentCount: number
  observationCount: number
  notes?: string
}

export interface QualitySummary {
  inspectionCount?: number
  passedCount?: number
  failedCount?: number
  notes?: string
}

export interface ProgressSummary {
  plannedQuantity?: number
  actualQuantity?: number
  unitOfMeasure?: string
  percentComplete?: number
  notes?: string
}

/**
 * Production daily report aggregate for the project-control domain.
 *
 * `reportNumber` must later be generated by a backend RPC, not by frontend
 * random generation. Future format example: `ORG-PROJ-2026-0001`.
 * Planned RPC: `generate_report_number(organization_id, project_id)`.
 *
 * Daily reports inherit soft delete, versioning, mobile/offline metadata, and
 * optimistic locking readiness from `BaseEntity`. Construction records should
 * use soft delete, not physical delete. Returned/resubmitted reports should use
 * version progression through `versionNumber` and `previousVersionId`.
 * Optimistic locking should compare `updatedAt` and/or `versionNumber` before
 * saving.
 *
 * Future database indexes should include:
 * - `organization_id, project_id, report_date`
 * - `organization_id, project_id, status`
 * - `organization_id, report_number`
 *
 * Linked records must be modeled with foreign-key-style fields, future junction
 * tables, or appropriate polymorphic references. Do not add relationship ID
 * arrays for attachments, inspections, NCRs, or corrective actions to this
 * aggregate.
 */
export interface DailyReport extends BaseEntity {
  reportNumber: string
  organizationId: EntityId
  projectId: EntityId
  reportDate: ISODateString
  timezone: string
  locale?: string
  status: DailyReportStatus
  submittedBy?: EntityId
  approvedBy?: EntityId
  submittedAt?: ISODateTimeString
  approvedAt?: ISODateTimeString
  returnedAt?: ISODateTimeString
  returnedReason?: string
  reviewComments?: string
  weatherLocation?: string
  weatherCondition?: string
  temperature?: number
  wind?: string
  precipitation?: string
  workSummary: WorkActivitySummary
  manpowerSummary: ManpowerSummary
  equipmentSummary: EquipmentSummary
  materialSummary: MaterialSummary
  delaySummary: DelaySummary
  safetySummary: SafetySummary
  qualitySummary: QualitySummary
  progressSummary: ProgressSummary
}

// Legacy Stage 2.1 local form types are retained to keep the current UI stable
// until the Stage 2.2 form architecture is implemented. They are intentionally
// separate from the production `DailyReport` aggregate above.
export type DailyReportFormStatus = 'draft' | 'submitted'

export type LegacyManpowerSummary = {
  plannedManpower: number
  actualManpower: number
  totalWorkHours: number
  contractorName: string
  supervisorName: string
}

export type WorkProgressItem = {
  id: string
  workCategory: WorkCategory | ''
  wbsActivityCode: string
  locationArea: string
  description: string
  plannedQuantity: number
  actualQuantity: number
  unit: QuantityUnit | ''
  progressPercent: number
  remarks: string
}

export type EquipmentItem = {
  id: string
  equipmentName: string
  equipmentNumber: string
  status: EquipmentStatus | ''
  workingHours: number
  breakdownHours: number
  remarks: string
}

export type HseSection = {
  toolboxTalkHeld: YesNo | ''
  toolboxTopic: string
  permitRequired: YesNo | ''
  permitNumbers: string

  incidentOccurred: YesNo | ''
  incidentType: string
  incidentDescription: string

  nearMissOccurred: YesNo | ''
  safetyObservation: string
  unsafeConditionCount: number
  unsafeActCount: number

  correctiveActionRequired: YesNo | ''
  correctiveActionDescription: string
  correctiveActionStatus: CorrectiveActionStatus | ''
}

export type QualityCheck = {
  id: string
  inspectionType: string
  result: QualityResult | ''
  nonConformanceFound: YesNo | ''
  ncrNumber: string
  remarks: string
}

export type DailyReportFormData = {
  reportDate: string
  projectSiteName: string
  preparedBy: string

  shiftType: ShiftType | ''
  shiftStartTime: string
  shiftEndTime: string

  weatherCondition: WeatherCondition | ''
  weatherRemarks: string

  // Temporary MVP compatibility fields.
  // These keep the current form working while we migrate to structured sections.
  manpowerCount: number
  workCompleted: string
  safetyObservation: string
  equipment: string
  attachmentNote: string

  status: DailyReportFormStatus

  manpower: LegacyManpowerSummary
  workItems: WorkProgressItem[]
  equipmentItems: EquipmentItem[]
  hse: HseSection
  qualityChecks: QualityCheck[]
}

export const createInitialDailyReportFormData = (): DailyReportFormData => ({
  reportDate: new Date().toISOString().slice(0, 10),
  projectSiteName: '',
  preparedBy: '',

  shiftType: '',
  shiftStartTime: '',
  shiftEndTime: '',

  weatherCondition: '',
  weatherRemarks: '',

  manpowerCount: 0,
  workCompleted: '',
  safetyObservation: '',
  equipment: '',
  attachmentNote: '',

  status: 'draft',

  manpower: {
    plannedManpower: 0,
    actualManpower: 0,
    totalWorkHours: 0,
    contractorName: '',
    supervisorName: '',
  },

  workItems: [
    {
      id: 'work-item-1',
      workCategory: '',
      wbsActivityCode: '',
      locationArea: '',
      description: '',
      plannedQuantity: 0,
      actualQuantity: 0,
      unit: '',
      progressPercent: 0,
      remarks: '',
    },
  ],

  equipmentItems: [
    {
      id: 'equipment-item-1',
      equipmentName: '',
      equipmentNumber: '',
      status: '',
      workingHours: 0,
      breakdownHours: 0,
      remarks: '',
    },
  ],

  hse: {
    toolboxTalkHeld: '',
    toolboxTopic: '',
    permitRequired: '',
    permitNumbers: '',

    incidentOccurred: '',
    incidentType: '',
    incidentDescription: '',

    nearMissOccurred: '',
    safetyObservation: '',
    unsafeConditionCount: 0,
    unsafeActCount: 0,

    correctiveActionRequired: '',
    correctiveActionDescription: '',
    correctiveActionStatus: '',
  },

  qualityChecks: [
    {
      id: 'quality-check-1',
      inspectionType: '',
      result: '',
      nonConformanceFound: '',
      ncrNumber: '',
      remarks: '',
    },
  ],
})
