import { z } from 'zod'
import type {
  CurrencyCode,
  DataResidencyRegion,
  MeasurementSystem,
  SubscriptionTier,
  SyncStatus,
} from '../../../types/common'
import type { DailyReportStatus } from '../../../types/dailyReport'

/**
 * Stage 2.2 Daily Report schemas for the production-grade global SaaS
 * foundation.
 *
 * Some fields are future-ready and may not appear in the current UI yet. The
 * current Stage 2.1 form remains supported through LegacyDailyReportFormSchema
 * while the production form model is introduced in controlled stages.
 *
 * `reportNumber` must later be generated by backend RPC, not frontend random
 * generation. Future RPC: generate_report_number(organization_id, project_id).
 *
 * Dynamic dashboard metrics are intentionally not part of DailyReport schemas.
 * Related Inspection, NCR, CorrectiveAction, and Attachment records must not be
 * stored as ID arrays inside DailyReport.
 *
 * Polymorphic reference integrity will later be enforced through application
 * validation, Zod schemas, backend RPC validation, or database triggers. Stage
 * 2.2 does not implement those integrity mechanisms.
 */

export const DailyReportStatusSchema = z.enum([
  'Draft',
  'Submitted',
  'InReview',
  'Approved',
  'Returned',
  'Rejected',
  'Archived',
]) satisfies z.ZodType<DailyReportStatus>

export const SyncStatusSchema = z.enum([
  'Synced',
  'PendingSync',
  'SyncFailed',
]) satisfies z.ZodType<SyncStatus>

export const CurrencyCodeSchema = z.enum([
  'MNT',
  'USD',
  'AUD',
  'SGD',
  'AED',
  'EUR',
  'GBP',
]) satisfies z.ZodType<CurrencyCode>

export const MeasurementSystemSchema = z.enum([
  'metric',
  'imperial',
]) satisfies z.ZodType<MeasurementSystem>

export const SubscriptionTierSchema = z.enum([
  'starter',
  'professional',
  'enterprise',
]) satisfies z.ZodType<SubscriptionTier>

export const DataResidencyRegionSchema = z.enum([
  'mn',
  'us',
  'eu',
  'au',
  'sg',
  'ae',
]) satisfies z.ZodType<DataResidencyRegion>

export const EntityIdSchema = z.string().trim().min(1, 'ID is required')

export const ISODateStringSchema = z
  .string()
  .trim()
  .regex(/^\d{4}-\d{2}-\d{2}$/, 'Date must use YYYY-MM-DD format')

export const ISODateTimeStringSchema = z
  .string()
  .trim()
  .min(1, 'Date/time is required')
  .refine((value) => !Number.isNaN(Date.parse(value)), {
    message: 'Date/time must be a valid ISO datetime string',
  })

export const PercentSchema = z.number().min(0).max(100)

export const NonNegativeNumberSchema = z.number().min(0)

export const OptionalNonNegativeNumberSchema = NonNegativeNumberSchema.optional()

export const OptionalTextSchema = z.string().trim().optional()

export const BaseEntitySchema = z.object({
  id: EntityIdSchema,
  organizationId: EntityIdSchema,
  projectId: EntityIdSchema.optional(),
  createdBy: EntityIdSchema,
  createdAt: ISODateTimeStringSchema,
  updatedAt: ISODateTimeStringSchema,
  isDeleted: z.boolean(),
  deletedAt: ISODateTimeStringSchema.optional(),
  deletedBy: EntityIdSchema.optional(),
  versionNumber: z.number().int().min(1),
  previousVersionId: EntityIdSchema.optional(),
  clientGeneratedId: EntityIdSchema.optional(),
  capturedAt: ISODateTimeStringSchema.optional(),
  syncStatus: SyncStatusSchema.optional(),
})

export const WorkActivitySummarySchema = z.object({
  workAreaId: EntityIdSchema.optional(),
  locationId: EntityIdSchema.optional(),
  disciplineId: EntityIdSchema.optional(),
  tradeId: EntityIdSchema.optional(),
  activityId: EntityIdSchema.optional(),
  costCode: OptionalTextSchema,
  wbsCode: OptionalTextSchema,
  description: z.string().trim().min(1, 'Work description is required'),
  plannedQuantity: OptionalNonNegativeNumberSchema,
  actualQuantity: OptionalNonNegativeNumberSchema,
  unitOfMeasure: OptionalTextSchema,
  percentComplete: PercentSchema.optional(),
})

const PermissiveEntrySchema = z.record(z.string(), z.unknown())

export const ManpowerSummarySchema = z.object({
  totalWorkers: NonNegativeNumberSchema,
  notes: OptionalTextSchema,
  entries: z.array(PermissiveEntrySchema).optional(),
})

export const EquipmentSummarySchema = z.object({
  totalEquipment: NonNegativeNumberSchema,
  notes: OptionalTextSchema,
  entries: z.array(PermissiveEntrySchema).optional(),
})

export const MaterialSummarySchema = z.object({
  notes: OptionalTextSchema,
  entries: z.array(PermissiveEntrySchema).optional(),
})

export const DelaySummarySchema = z.object({
  hasDelay: z.boolean(),
  delayHours: OptionalNonNegativeNumberSchema,
  reason: OptionalTextSchema,
  responsibleParty: OptionalTextSchema,
  impact: OptionalTextSchema,
  mitigation: OptionalTextSchema,
})

export const SafetySummarySchema = z.object({
  incidentCount: NonNegativeNumberSchema.default(0),
  observationCount: NonNegativeNumberSchema.default(0),
  notes: OptionalTextSchema,
})

export const QualitySummarySchema = z.object({
  inspectionCount: OptionalNonNegativeNumberSchema,
  passedCount: OptionalNonNegativeNumberSchema,
  failedCount: OptionalNonNegativeNumberSchema,
  notes: OptionalTextSchema,
})

export const ProgressSummarySchema = z.object({
  plannedQuantity: OptionalNonNegativeNumberSchema,
  actualQuantity: OptionalNonNegativeNumberSchema,
  unitOfMeasure: OptionalTextSchema,
  percentComplete: PercentSchema.optional(),
  notes: OptionalTextSchema,
})

/**
 * Production form input schema.
 *
 * Backend-generated BaseEntity fields are intentionally excluded here. They are
 * required only by DailyReportPersistedSchema after a report exists in storage.
 */
export const DailyReportFormSchema = z.object({
  organizationId: EntityIdSchema,
  projectId: EntityIdSchema,
  reportDate: ISODateStringSchema,
  timezone: z.string().trim().min(1, 'Timezone is required'),
  status: DailyReportStatusSchema,
  locale: OptionalTextSchema,
  weatherLocation: OptionalTextSchema,
  weatherCondition: OptionalTextSchema,
  temperature: z.number().optional(),
  wind: OptionalTextSchema,
  precipitation: OptionalTextSchema,
  workSummary: WorkActivitySummarySchema.optional(),
  manpowerSummary: ManpowerSummarySchema.optional(),
  equipmentSummary: EquipmentSummarySchema.optional(),
  materialSummary: MaterialSummarySchema.optional(),
  delaySummary: DelaySummarySchema.optional(),
  safetySummary: SafetySummarySchema.optional(),
  qualitySummary: QualitySummarySchema.optional(),
  progressSummary: ProgressSummarySchema.optional(),
})

export const DailyReportPersistedSchema = BaseEntitySchema.extend({
  reportNumber: z.string().trim().min(1, 'Report number is required'),
  organizationId: EntityIdSchema,
  projectId: EntityIdSchema,
  reportDate: ISODateStringSchema,
  timezone: z.string().trim().min(1, 'Timezone is required'),
  locale: OptionalTextSchema,
  status: DailyReportStatusSchema,
  submittedBy: EntityIdSchema.optional(),
  approvedBy: EntityIdSchema.optional(),
  submittedAt: ISODateTimeStringSchema.optional(),
  approvedAt: ISODateTimeStringSchema.optional(),
  returnedAt: ISODateTimeStringSchema.optional(),
  returnedReason: OptionalTextSchema,
  reviewComments: OptionalTextSchema,
  weatherLocation: OptionalTextSchema,
  weatherCondition: OptionalTextSchema,
  temperature: z.number().optional(),
  wind: OptionalTextSchema,
  precipitation: OptionalTextSchema,
  workSummary: WorkActivitySummarySchema,
  manpowerSummary: ManpowerSummarySchema,
  equipmentSummary: EquipmentSummarySchema,
  materialSummary: MaterialSummarySchema,
  delaySummary: DelaySummarySchema,
  safetySummary: SafetySummarySchema,
  qualitySummary: QualitySummarySchema,
  progressSummary: ProgressSummarySchema,
})

export const LegacyDailyReportFormSchema = z.object({
  reportDate: ISODateStringSchema,
  projectSiteName: z.string(),
  preparedBy: z.string(),
  shiftType: z.enum(['day', 'night', 'other', '']),
  shiftStartTime: z.string(),
  shiftEndTime: z.string(),
  weatherCondition: z.enum([
    'clear',
    'cloudy',
    'rain',
    'snow',
    'windy',
    'storm',
    'other',
    '',
  ]),
  weatherRemarks: z.string(),
  manpowerCount: NonNegativeNumberSchema,
  workCompleted: z.string(),
  safetyObservation: z.string(),
  equipment: z.string(),
  attachmentNote: z.string(),
  status: z.enum(['draft', 'submitted']),
})

export type DailyReportFormInput = z.infer<typeof DailyReportFormSchema>
export type DailyReportPersistedInput = z.infer<typeof DailyReportPersistedSchema>
export type WorkActivitySummaryInput = z.infer<
  typeof WorkActivitySummarySchema
>
export type ManpowerSummaryInput = z.infer<typeof ManpowerSummarySchema>
export type EquipmentSummaryInput = z.infer<typeof EquipmentSummarySchema>
export type MaterialSummaryInput = z.infer<typeof MaterialSummarySchema>
export type DelaySummaryInput = z.infer<typeof DelaySummarySchema>
export type SafetySummaryInput = z.infer<typeof SafetySummarySchema>
export type QualitySummaryInput = z.infer<typeof QualitySummarySchema>
export type ProgressSummaryInput = z.infer<typeof ProgressSummarySchema>
export type LegacyDailyReportFormInput = z.infer<
  typeof LegacyDailyReportFormSchema
>
